// Generated by gencpp from file maggie_board_comm/board_cmd.msg
// DO NOT EDIT!


#ifndef MAGGIE_BOARD_COMM_MESSAGE_BOARD_CMD_H
#define MAGGIE_BOARD_COMM_MESSAGE_BOARD_CMD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace maggie_board_comm
{
template <class ContainerAllocator>
struct board_cmd_
{
  typedef board_cmd_<ContainerAllocator> Type;

  board_cmd_()
    : isLeftLegOnline(false)
    , isRightLegOnline(false)
    , isRobotOnGround(false)
    , enableWheel(false)  {
    }
  board_cmd_(const ContainerAllocator& _alloc)
    : isLeftLegOnline(false)
    , isRightLegOnline(false)
    , isRobotOnGround(false)
    , enableWheel(false)  {
  (void)_alloc;
    }



   typedef uint8_t _isLeftLegOnline_type;
  _isLeftLegOnline_type isLeftLegOnline;

   typedef uint8_t _isRightLegOnline_type;
  _isRightLegOnline_type isRightLegOnline;

   typedef uint8_t _isRobotOnGround_type;
  _isRobotOnGround_type isRobotOnGround;

   typedef uint8_t _enableWheel_type;
  _enableWheel_type enableWheel;





  typedef boost::shared_ptr< ::maggie_board_comm::board_cmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::maggie_board_comm::board_cmd_<ContainerAllocator> const> ConstPtr;

}; // struct board_cmd_

typedef ::maggie_board_comm::board_cmd_<std::allocator<void> > board_cmd;

typedef boost::shared_ptr< ::maggie_board_comm::board_cmd > board_cmdPtr;
typedef boost::shared_ptr< ::maggie_board_comm::board_cmd const> board_cmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::maggie_board_comm::board_cmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::maggie_board_comm::board_cmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::maggie_board_comm::board_cmd_<ContainerAllocator1> & lhs, const ::maggie_board_comm::board_cmd_<ContainerAllocator2> & rhs)
{
  return lhs.isLeftLegOnline == rhs.isLeftLegOnline &&
    lhs.isRightLegOnline == rhs.isRightLegOnline &&
    lhs.isRobotOnGround == rhs.isRobotOnGround &&
    lhs.enableWheel == rhs.enableWheel;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::maggie_board_comm::board_cmd_<ContainerAllocator1> & lhs, const ::maggie_board_comm::board_cmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace maggie_board_comm

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::maggie_board_comm::board_cmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::maggie_board_comm::board_cmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::maggie_board_comm::board_cmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::maggie_board_comm::board_cmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::maggie_board_comm::board_cmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::maggie_board_comm::board_cmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::maggie_board_comm::board_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "88619d4843913e77ca2a39023d862f3a";
  }

  static const char* value(const ::maggie_board_comm::board_cmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x88619d4843913e77ULL;
  static const uint64_t static_value2 = 0xca2a39023d862f3aULL;
};

template<class ContainerAllocator>
struct DataType< ::maggie_board_comm::board_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "maggie_board_comm/board_cmd";
  }

  static const char* value(const ::maggie_board_comm::board_cmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::maggie_board_comm::board_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool isLeftLegOnline\n"
"bool isRightLegOnline\n"
"bool isRobotOnGround\n"
"bool enableWheel\n"
;
  }

  static const char* value(const ::maggie_board_comm::board_cmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::maggie_board_comm::board_cmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.isLeftLegOnline);
      stream.next(m.isRightLegOnline);
      stream.next(m.isRobotOnGround);
      stream.next(m.enableWheel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct board_cmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::maggie_board_comm::board_cmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::maggie_board_comm::board_cmd_<ContainerAllocator>& v)
  {
    s << indent << "isLeftLegOnline: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isLeftLegOnline);
    s << indent << "isRightLegOnline: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isRightLegOnline);
    s << indent << "isRobotOnGround: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isRobotOnGround);
    s << indent << "enableWheel: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enableWheel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAGGIE_BOARD_COMM_MESSAGE_BOARD_CMD_H
