(cl:in-package maggie_board_comm-msg)
(cl:export '(ISLEFTWHEELONLINE-VAL
          ISLEFTWHEELONLINE
          ISRIGHTWHEELONLINE-VAL
          ISRIGHTWHEELONLINE
          ISWHEELENABLED-VAL
          ISWHEELENABLED
          ISFORCESHUTDOWNTRIGGERED-VAL
          ISFORCESHUTDOWNTRIGGERED
          TILTANGLE-VAL
          TILTANGLE
          ZMOVE-VAL
          ZMOVE
))