# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from maggie_board_comm/board_cmd.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class board_cmd(genpy.Message):
  _md5sum = "88619d4843913e77ca2a39023d862f3a"
  _type = "maggie_board_comm/board_cmd"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """bool isLeftLegOnline
bool isRightLegOnline
bool isRobotOnGround
bool enableWheel"""
  __slots__ = ['isLeftLegOnline','isRightLegOnline','isRobotOnGround','enableWheel']
  _slot_types = ['bool','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       isLeftLegOnline,isRightLegOnline,isRobotOnGround,enableWheel

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(board_cmd, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.isLeftLegOnline is None:
        self.isLeftLegOnline = False
      if self.isRightLegOnline is None:
        self.isRightLegOnline = False
      if self.isRobotOnGround is None:
        self.isRobotOnGround = False
      if self.enableWheel is None:
        self.enableWheel = False
    else:
      self.isLeftLegOnline = False
      self.isRightLegOnline = False
      self.isRobotOnGround = False
      self.enableWheel = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4B().pack(_x.isLeftLegOnline, _x.isRightLegOnline, _x.isRobotOnGround, _x.enableWheel))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 4
      (_x.isLeftLegOnline, _x.isRightLegOnline, _x.isRobotOnGround, _x.enableWheel,) = _get_struct_4B().unpack(str[start:end])
      self.isLeftLegOnline = bool(self.isLeftLegOnline)
      self.isRightLegOnline = bool(self.isRightLegOnline)
      self.isRobotOnGround = bool(self.isRobotOnGround)
      self.enableWheel = bool(self.enableWheel)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4B().pack(_x.isLeftLegOnline, _x.isRightLegOnline, _x.isRobotOnGround, _x.enableWheel))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 4
      (_x.isLeftLegOnline, _x.isRightLegOnline, _x.isRobotOnGround, _x.enableWheel,) = _get_struct_4B().unpack(str[start:end])
      self.isLeftLegOnline = bool(self.isLeftLegOnline)
      self.isRightLegOnline = bool(self.isRightLegOnline)
      self.isRobotOnGround = bool(self.isRobotOnGround)
      self.enableWheel = bool(self.enableWheel)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4B = None
def _get_struct_4B():
    global _struct_4B
    if _struct_4B is None:
        _struct_4B = struct.Struct("<4B")
    return _struct_4B
